### ISSUE TITLE
Vuex example

### ISSUE THREAD

**Issue by iskrisis** [lrembacz/vue-responsive-grid-layout#8]
I am not sure how much differences there are compared to vue-grid-layout but you mentioned that it is possible to use with vuex. I need to have layout in store but i am having difficulties figuring out how to use it this way. 

Would it be possible to provide also vuex demo? I think it would help documentation aswell.

Thank you so much by the way. Awesome project.

**Comment by lrembacz** [comment]
I've made some changes meanwhile and I need to make this project updated. The Vuex part is now more like on DEV branch so state of layouts is taken directly from Vuex (layouts are only props) and events to change size of all elements and positions are queued inside component in my queue mechanism. 

I'll try to fix some issues and update everything. After that I'll make demo and I'm planning to post example project with Laravel as well, but I need more free time for this.

If I find time this weekend I will do it. However, I do not promise because I also have a few things to do.

Thanks for your support!

**Comment by iskrisis** [comment]
No rush. It is already great work.

**Comment by lrembacz** [comment]
Dev branch is making many changes and I'm about to finish this. There is Vuex + Typescript example.
